spring:
  application:
    name: eureka-provider
  kafka:
    bootstrap-servers:
    #配置kafka集群
      - 192.168.26.128:9092
      - 192.168.26.128:9093
      - 192.168.26.128:9094
    #配置生产者  
    producer:
      #尝试的次数
      retries: 0  
      #缓存大小
      buffer-memory: 33554432
    #配置消费者
    consumer:
      #使listenGroup有两个消费者
      group-id: listenGroup
      enable-auto-commit: true
      #设置分区的偏移量
      auto-offset-reset: earliest 
      #下面是kafka-client版本造成的错误
#      key-deserializer:
#        org.apache.kafka.common.serialization.StringSerializer
#      value-deserializer:
#        org.apache.kafka.common.serialization.StringSerializer
    
server:
  port: 9004
  
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.2:9003/eureka
  instance:
     #以ip的方式与服务名称或是id进行映射
     prefer-ip-address: true 
     #注册eureka中的id名称
     instance-id: ${spring.application.name}:${server.port}

      